<div class="p-4">
  <div class="w-full h-30 overflow-y-auto">
    {#each eventLogs as { log, color }, index (index)}
      <p style="color: { color }">{ log }</p>
    {/each}
  </div>

  <br />

  {#if machine.display}
    <div>
      <canvas width={ machine.display.displaySize[0] * 10 }
              height={ machine.display.displaySize[1] * 10 }
              bind:this={ canvasElement }
              class="border border-gray-500"></canvas>
    </div>
  {/if}

  <p>Cycle: { cycle }</p>
  <p>Real execution time per cycle: { cycleTime } ms</p>

  <br />

  <button onclick={ () => machine.processor.stop() } class="p-2 border border-gray-500">Stop</button>
  <button onclick={ () => machine.processor.start() } class="p-2 border border-gray-500">Start</button>
  <button onclick={ () => loadFromFile() } class="p-2 border border-gray-500">Load ROM from file</button>
  <input bind:files={ romFile } type="file" accept=".bin, .rom, .ch8">

  <br />

  <p>Memory reads: { memoryReads }</p>
  <p>Memory writes: { memoryWrites }</p>

  <br />

  {#if dump}
    <p>Register dump:</p>

    {#each Object.entries(dump) as [ key, value ] (key)}
      {#if typeof value === "object" && value instanceof Array}
        <div>{ key }: [ <pre>{ value.map((v, i) => `  #${i.toString(16).toUpperCase()}: 0x${v.toString(16).toUpperCase().padStart(2, "0")}`).join("\n") }</pre> ]</div>
      {:else}
        <div>{ key } : <code>0x{ value.toString(16).toUpperCase().padStart(4, "0") }</code></div>
      {/if}
    {/each}
  {/if}
</div>


<script lang="ts">
import { Chip8Event, Chip8Machine, type Chip8EventDetailTypeMap } from "@somni/chip8-emulator-core";
import { onMount } from "svelte";

//// NOTE: Test ROMs are generated by Google Gemini
// The "Awesome C8" Test ROM.
// Executes ALL opcodes (except Ex9E, ExA1, Fx0A) and draws "C8" on the screen.
// Assuming the program is loaded at memory address 0x200.
// Standard CHIP-8 font set must be loaded in memory!
const awesomeTestRom = new Uint8Array([
  // --- 1. Clear Screen ---
  0x00, 0xE0, // 0x200: CLS           - Wipe the canvas clean!

  // --- 2. Setup Drawing Coordinates ---
  0x6A, 0x0A, // 0x202: LD VA, 10     - VA = 10 (X coord for 'C')
  0x6B, 0x14, // 0x204: LD VB, 20     - VB = 20 (X coord for '8')
  0x6C, 0x0A, // 0x206: LD VC, 10     - VC = 10 (Y coord for both)

  // --- 3. Fire up the Timers ---
  0x60, 0xFF, // 0x208: LD V0, 255    - V0 = 255
  0xF0, 0x15, // 0x20A: LD DT, V0     - Delay Timer = 255
  0xF0, 0x18, // 0x20C: LD ST, V0     - Sound Timer = 255
  0xF0, 0x07, // 0x20E: LD V0, DT     - Read DT back into V0

  // --- 4. Draw 'C' ---
  0x61, 0x0C, // 0x210: LD V1, 0x0C   - V1 = Hex digit 'C' (12)
  0xF1, 0x29, // 0x212: LD F, V1      - Point I to font 'C'
  0xDA, 0xC5, // 0x214: DRW VA, VC, 5 - Draw 'C' at (10, 10)

  // --- 5. Draw '8' ---
  0x61, 0x08, // 0x216: LD V1, 0x08   - V1 = Hex digit '8' (8)
  0xF1, 0x29, // 0x218: LD F, V1      - Point I to font '8'
  0xDB, 0xC5, // 0x21A: DRW VB, VC, 5 - Draw '8' at (20, 10)

  // --- 6. Deterministic ALU & Skip Gauntlet ---
  0xC2, 0x00, // 0x21C: RND V2, 0     - V2 = Random & 0 = 0
  0x72, 0x01, // 0x21E: ADD V2, 1     - V2 = 1
  0x32, 0x01, // 0x220: SE V2, 1      - Skip next (1 == 1)
  0x12, 0x5C, // 0x222: JP 0x25C      - TRAP!
  0x42, 0x00, // 0x224: SNE V2, 0     - Skip next (1 != 0)
  0x12, 0x5C, // 0x226: JP 0x25C      - TRAP!

  // --- 7. The 8xyN Operations ---
  0x82, 0x20, // 0x228: LD V2, V2     - V2 = 1
  0x82, 0x21, // 0x22A: OR V2, V2     - V2 = 1 | 1 = 1
  0x82, 0x22, // 0x22C: AND V2, V2    - V2 = 1 & 1 = 1
  0x82, 0x23, // 0x22E: XOR V2, V2    - V2 = 1 ^ 1 = 0 (V2 is now 0!)
  0x82, 0x24, // 0x230: ADD V2, V2    - V2 = 0 + 0 = 0
  0x82, 0x25, // 0x232: SUB V2, V2    - V2 = 0 - 0 = 0
  0x82, 0x26, // 0x234: SHR V2, V2    - V2 = 0 >> 1 = 0
  0x82, 0x27, // 0x236: SUBN V2, V2   - V2 = 0 - 0 = 0
  0x82, 0x2E, // 0x238: SHL V2, V2    - V2 = 0 << 1 = 0

  // --- 8. Register Skips ---
  0x52, 0x20, // 0x23A: SE V2, V2     - Skip next (0 == 0)
  0x12, 0x5C, // 0x23C: JP 0x25C      - TRAP!
  0x63, 0x01, // 0x23E: LD V3, 1      - V3 = 1
  0x92, 0x30, // 0x240: SNE V2, V3    - Skip next (0 != 1)
  0x12, 0x5C, // 0x242: JP 0x25C      - TRAP!

  // --- 9. Memory & BCD Mastery ---
  0x64, 0xFF, // 0x244: LD V4, 255    - V4 = 255
  0xA3, 0x00, // 0x246: LD I, 0x300   - I = 0x300
  0xF4, 0x33, // 0x248: LD B, V4      - Store BCD (2, 5, 5) at 0x300~0x302
  0xF4, 0x55, // 0x24A: LD [I], V4    - Dump V0~V4 to memory
  0xF4, 0x65, // 0x24C: LD V4, [I]    - Read them back
  0xF4, 0x1E, // 0x24E: ADD I, V4     - I = 0x300 + 255 = 0x3FF

  // --- 10. Subroutine & Offset Jump ---
  0x22, 0x5E, // 0x250: CALL 0x25E    - Push 0x252 to stack, jump to 0x25E
  // (Returns here)
  0x60, 0x02, // 0x252: LD V0, 2      - V0 = 2
  0xB2, 0x56, // 0x254: JP V0, 0x256  - PC = 0x256 + V0(2) = 0x258 (Jumps over NOP!)
  0x00, 0x00, // 0x256: NOP           - This should be skipped

  // --- 11. Success End ---
  0x12, 0x58, // 0x258: JP 0x258      - SUCCESS! Infinite loop.

  // --- Error Trap End ---
  0x00, 0x00, // 0x25A: NOP
  0x12, 0x5C, // 0x25C: JP 0x25C      - FAIL! Caught in the trap.

  // --- Subroutine Definition ---
  0x65, 0x42, // 0x25E: LD V5, 0x42   - Subroutine logic: V5 = 0x42
  0x00, 0xEE,  // 0x260: RET           - Pop stack, return to 0x252
]);

let canvasElement: HTMLCanvasElement | null = null;
let dump: ReturnType<typeof machine.processor.dumpRegisters> | null = $state(null);
let cycle: string = $state("");
let cycleTime: string = $state("");
let memoryReads: string = $state("");
let memoryWrites: string = $state("");
let eventLogs: { log: string, color: string }[] = $state([]);
let romFile: FileList | null = $state(null);

const machine = $state(new Chip8Machine({ eventBusLogger: addEventLog }));
machine.loadProgram(awesomeTestRom);
machine.processor.start();
machine.eventBus?.subscribe(Chip8Event.DISPLAY_CLEAR, clearDisplayCanvas);
machine.eventBus?.subscribe(Chip8Event.DISPLAY_SET_PIXEL, updateDisplayCanvas);

onMount(() => {
  const interval = setInterval(() => {
    dump = machine.processor.dumpRegisters();
    cycle = machine.processor.totalCyclesExecuted.toString();
    cycleTime = machine.processor.currentCycleDuration.toFixed(2);
    memoryReads = machine.memory.totalBytesRead.toString();
    memoryWrites = machine.memory.totalBytesWritten.toString();

    //updateDisplayCanvasAlt();
  }, 1000 / 60);
});

function addEventLog(message: string, eventName?: string, eventDetail?: unknown) {
  let color = "#000000";

  if(message.includes("EMIT")) {
    if(eventName?.includes("PANIC")) {
      color = "#FF0000";
    } else if(eventName?.includes("ERROR")) {
      color = "#FF0099";
    } else if(eventName?.includes("WARN")) {
      color = "#FF9900";
    }
  }

  eventLogs.unshift({ log: message, color });
}

function loadFromFile() {
  if(!romFile || romFile.length === 0) {
    alert("no file");
    return;
  }

  const file = romFile[0];
  const reader = new FileReader();
  reader.onloadend = () => {
    if(reader.result instanceof ArrayBuffer) {
      machine.clear();
      machine.loadProgram(new Uint8Array(reader.result));
      alert(`Loaded ROM from file: ${file.name}, press Start button to run`);
    } else {
      alert("file error");
    }
  };
  reader.readAsArrayBuffer(file);
}

function clearDisplayCanvas() {
  if(!canvasElement) return;

  const ctx = canvasElement.getContext("2d");
  if(!ctx) return;

  ctx.clearRect(0, 0, canvasElement.width, canvasElement.height);
}

function updateDisplayCanvas(event: Event) {
  if(!canvasElement) return;

  const eventData = (event as CustomEvent).detail as Chip8EventDetailTypeMap[Chip8Event.DISPLAY_SET_PIXEL];

  const ctx = canvasElement.getContext("2d");
  if(!ctx) return;

  if(eventData.value >= 1) {
    ctx.fillRect(eventData.x * 10, eventData.y * 10, 10, 10);
  } else {
    ctx.clearRect(eventData.x * 10, eventData.y * 10, 10, 10);
  }
}

function updateDisplayCanvasAlt() {
  if(!canvasElement) return;

  const dump = machine.display.dump();

  const ctx = canvasElement.getContext("2d");
  if(!ctx) return;

  for(let y = 0; y < dump.length; y++) {
    for(let x = 0; x < dump[y].length; x++) {
      if(dump[y][x] >= 1) {
        ctx.fillRect(x * 10, y * 10, 10, 10);
      } else {
        ctx.clearRect(x * 10, y * 10, 10, 10);
      }
    }
  }
}
</script>
