<div class="p-4">
  <div class="w-full h-30 overflow-y-auto">
    {#each eventLogs as { log, color }, index (index)}
      <p style="color: { color }">{ log }</p>
    {/each}
  </div>

  <br />

  {#if machine.display}
    <div>
      <canvas width={ machine.display.displaySize[0] * 10 }
              height={ machine.display.displaySize[1] * 10 }
              bind:this={ canvasElement }
              class="border border-gray-500"></canvas>
    </div>
  {/if}

  <p>Cycle: { cycle }</p>
  <p>Real execution time per cycle: { cycleTime } ms</p>

  <br />

  <button onclick={ () => machine.processor.stop() } class="p-2 border border-gray-500">Stop</button>
  <button onclick={ () => machine.processor.start() } class="p-2 border border-gray-500">Start</button>
  <button onclick={ () => loadFromFile() } class="p-2 border border-gray-500">Load ROM from file</button>
  <input bind:files={ romFile } type="file" accept=".bin, .rom, .ch8">

  <br />

  <p>Memory reads: { memoryReads }</p>
  <p>Memory writes: { memoryWrites }</p>

  <br />

  {#if dump}
    <p>Register dump:</p>

    {#each Object.entries(dump) as [ key, value ] (key)}
      {#if typeof value === "object" && value instanceof Array}
        <div>{ key }: [ <pre>{ value.map((v, i) => `  #${i.toString(16).toUpperCase()}: 0x${v.toString(16).toUpperCase().padStart(2, "0")}`).join("\n") }</pre> ]</div>
      {:else}
        <div>{ key } : <code>0x{ value.toString(16).toUpperCase().padStart(4, "0") }</code></div>
      {/if}
    {/each}
  {/if}
</div>


<script lang="ts">
import { Chip8Event, Chip8Machine } from "@somni/chip8-emulator-core";
import { onMount } from "svelte";

//// NOTE: Test ROMs are generated by Google Gemini
// Comprehensive, deterministic CHIP-8 test ROM.
// Assuming the program is loaded at memory address 0x200.
const deterministicTestRom = new Uint8Array([
  0x60, 0x00, // 0x200: LD V0, 0     - Initialize V0 to 0
  0x61, 0xA5, // 0x202: LD V1, 0xA5  - V1 = 165 (10100101 in binary)
  0x62, 0x5A, // 0x204: LD V2, 0x5A  - V2 =  90 (01011010 in binary)

  // 1. Logical Operations
  0x81, 0x21, // 0x206: OR V1, V2    - V1 = V1 | V2 (becomes 0xFF)
  0x82, 0x12, // 0x208: AND V2, V1   - V2 = V2 & V1 (0x5A & 0xFF becomes 0x5A)
  0x82, 0x13, // 0x20A: XOR V2, V1   - V2 = V2 ^ V1 (0x5A ^ 0xFF becomes 0xA5)

  // 2. Math Operations (Addition with Carry)
  0x63, 0x80, // 0x20C: LD V3, 0x80  - V3 = 128
  0x64, 0x81, // 0x20E: LD V4, 0x81  - V4 = 129
  0x83, 0x44, // 0x210: ADD V3, V4   - V3 = V3 + V4. 128 + 129 = 257. V3 = 0x01, VF = 1 (Carry)

  // 3. Math Operations (Subtraction with Borrow)
  0x65, 0x0A, // 0x212: LD V5, 0x0A  - V5 = 10
  0x66, 0x0C, // 0x214: LD V6, 0x0C  - V6 = 12
  0x85, 0x65, // 0x216: SUB V5, V6   - V5 = V5 - V6. 10 - 12 = -2. V5 = 0xFE, VF = 0 (Borrow occurred)

  // 4. Subroutine Call
  0xA5, 0x55, // 0x218: LD I, 0x555  - I = 0x555
  0x22, 0x30, // 0x21A: CALL 0x230   - Push 0x21C to stack, set PC = 0x230

  // 5. Return Target & Offset Jump
  0x60, 0x04, // 0x21C: LD V0, 4     - Set V0 to 4 to prepare for offset jump
  0xB2, 0x22, // 0x21E: JP V0, 0x222 - PC = 0x222 + V0 (4) = 0x226

  // --- Error Traps ---
  0x12, 0x20, // 0x220: JP 0x220     - Trap 1 (Fell through JP V0)
  0x12, 0x22, // 0x222: JP 0x222     - Trap 2 (Jumped with V0 = 0)
  0x12, 0x24, // 0x224: JP 0x224     - Trap 3 (Jumped with V0 = 2)

  // --- Success Target ---
  0x12, 0x26, // 0x226: JP 0x226     - Success! Infinite loop safely halts execution.

  // --- Padding to align subroutine exactly at 0x230 ---
  0x00, 0x00, // 0x228: NOP
  0x00, 0x00, // 0x22A: NOP
  0x00, 0x00, // 0x22C: NOP
  0x00, 0x00, // 0x22E: NOP

  // --- Subroutine Definition (0x230) ---
  0x77, 0x11, // 0x230: ADD V7, 0x11 - V7 = V7 + 17 (0x11). 7XKK does NOT affect VF flag!
  0x88, 0x70, // 0x232: LD V8, V7    - V8 = V7 (0x11)
  0x00, 0xEE, // 0x234: RET          - Pop stack (0x21C), set PC = 0x21C
]);

// A deterministic CHIP-8 test program to verify LD [I], Vx (Fx55) and LD Vx, [I] (Fx65).
// Assuming the program is loaded at memory address 0x200.
const memoryIoTestRom = new Uint8Array([
  // --- 1. Setup initial values in V0, V1, V2 ---
  0x60, 0xAA, // 0x200: LD V0, 0xAA - V0 = 170
  0x61, 0xBB, // 0x202: LD V1, 0xBB - V1 = 187
  0x62, 0xCC, // 0x204: LD V2, 0xCC - V2 = 204

  // --- 2. Save registers to memory ---
  0xA3, 0x00, // 0x206: LD I, 0x300 - Set I pointer to a safe empty memory area (0x300)
  0xF2, 0x55, // 0x208: LD [I], V2  - Save V0, V1, V2 to memory starting at 0x300

  // --- 3. Clear registers to prove we are actually loading from memory ---
  0x60, 0x00, // 0x20A: LD V0, 0    - V0 = 0
  0x61, 0x00, // 0x20C: LD V1, 0    - V1 = 0
  0x62, 0x00, // 0x20E: LD V2, 0    - V2 = 0

  // --- 4. Load registers back from memory ---
  0xA3, 0x00, // 0x210: LD I, 0x300 - Reset I to 0x300 (See quirk note below!)
  0xF2, 0x65, // 0x212: LD V2, [I]  - Load V0, V1, V2 from memory starting at 0x300

  // --- 5. End of Program ---
  0x12, 0x14,  // 0x214: JP 0x214    - Infinite loop to halt safely
]);

// A deterministic CHIP-8 test program to verify LD B, Vx (Fx33).
// Assuming the program is loaded at memory address 0x200.
const bcdTestRom = new Uint8Array([
  // --- 1. Setup ---
  0x60, 0xFF, // 0x200: LD V0, 255 (0xFF) - A 3-digit number
  0x61, 0x2A, // 0x202: LD V1, 42  (0x2A) - A 2-digit number

  // --- 2. BCD of V0 (255) ---
  0xA3, 0x00, // 0x204: LD I, 0x300 - Set I to memory address 0x300
  0xF0, 0x33, // 0x206: LD B, V0    - Store BCD of 255 at I, I+1, I+2

  // --- 3. BCD of V1 (42) ---
  0xA3, 0x04, // 0x208: LD I, 0x304 - Set I to memory address 0x304
  0xF1, 0x33, // 0x20A: LD B, V1    - Store BCD of 42 at I, I+1, I+2

  // --- 4. Halt ---
  0x12, 0x0C, // 0x20C: JP 0x20C    - Infinite loop to halt safely
]);

let canvasElement: HTMLCanvasElement | null = null;
let dump: ReturnType<typeof machine.processor.dumpRegisters> | null = $state(null);
let cycle: string = $state("");
let cycleTime: string = $state("");
let memoryReads: string = $state("");
let memoryWrites: string = $state("");
let eventLogs: { log: string, color: string }[] = $state([]);
let romFile: FileList | null = $state(null);

const machine = $state(new Chip8Machine({ eventBusLogger: addEventLog }));
machine.loadProgram(bcdTestRom);
machine.processor.start();
machine.eventBus.subscribe(Chip8Event.DISPLAY_SET_PIXEL, updateDisplayCanvas);

onMount(() => {
  const interval = setInterval(() => {
    dump = machine.processor.dumpRegisters();
    cycle = machine.processor.totalCyclesExecuted.toString();
    cycleTime = machine.processor.currentCycleDuration.toFixed(2);
    memoryReads = machine.memory.totalBytesRead.toString();
    memoryWrites = machine.memory.totalBytesWritten.toString();
  }, 1000 / 60);
});

function addEventLog(message: string, eventName?: string, eventDetail?: unknown) {
  let color = "#000000";

  if(message.includes("EMIT")) {
    if(eventName?.includes("PANIC")) {
      color = "#FF0000";
    } else if(eventName?.includes("ERROR")) {
      color = "#FF0099";
    } else if(eventName?.includes("WARN")) {
      color = "#FF9900";
    }
  }

  eventLogs.unshift({ log: message, color });
}

function loadFromFile() {
  if(!romFile || romFile.length === 0) {
    alert("no file");
    return;
  }

  const file = romFile[0];
  const reader = new FileReader();
  reader.onloadend = () => {
    if(reader.result instanceof ArrayBuffer) {
      machine.clear();
      machine.loadProgram(new Uint8Array(reader.result));
      alert(`Loaded ROM from file: ${file.name}, press Start button to run`);
    } else {
      alert("file error");
    }
  };
  reader.readAsArrayBuffer(file);
}

function updateDisplayCanvas() {
  if(!canvasElement) return;

  const ctx = canvasElement.getContext("2d");
  if(!ctx) return;

  const displayData = machine.display.dump();
  if(!displayData) return;

  // TODO
}
</script>
